### ISSUE TITLE
赞！

### ISSUE THREAD

**Issue by jiyupack** [liujianjia/12306ticket#1]
邮件发送不成功！

**Comment by zezeez** [comment]
Which mail box do you have set?Yeah, there is some problem known about 163 mail box and haven't good solutions now, but tested gmail,outlook and qq mail box is fine, of course gmail isn't available at China, consider using outlook or qq mail box if you have one, or you can try other untested mail box .

**Comment by jiyupack** [comment]
Hi,My config file is set to QQ mail and it works fine today.May be due to network problems when testing yesterday.Thanks!
